name: Build and Release Beta

on:
  push:
    branches: [beta]

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:  # 添加必要的权限
      contents: write

    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v4

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: 安装依赖项
      run: |
        python -m pip install --upgrade pip
        pip install PyInstaller PySide6

    - name: 运行 PyInstaller 打包
      run: pyinstaller main.spec

    - name: 查找并重命名可执行文件
      shell: pwsh
      run: |
        # 查找 dist 目录中的可执行文件
        $exe = Get-ChildItem -Path dist -Filter *.exe -Recurse | Select-Object -First 1
        
        if (-not $exe) {
            Write-Error "未在 dist 目录中找到 .exe 文件"
            exit 1
        }
        
        # 重命名文件以包含 commit SHA
        $newName = "ScoreManager-beta-${{ github.sha }}.exe"
        Rename-Item -Path $exe.FullName -NewName $newName
        
        # 设置环境变量供后续步骤使用
        echo "EXE_PATH=dist/$newName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: 验证 EXE 文件存在
      run: |
        dir ${{ env.EXE_PATH }}
        if not exist ${{ env.EXE_PATH }} (
          echo "错误：可执行文件不存在！"
          exit 1
        )

    - name: 创建 GitHub 发布版本
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: "beta-${{ github.sha }}"
        name: "Beta 版本 (${{ github.sha }})"
        body: "自动构建的 beta 版本，对应提交 ${{ github.sha }}"
        files: ${{ env.EXE_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}